steps:
- name: hashicorp/terraform
   dir: deployments/
   args: ['init']
- name: hashicorp/terraform
  dir: deployments/
  args: ['plan','-out=terraform.tfplan']
- name: hashicorp/terraform
  dir: deployments/
  args: ['apply','-auto-approve']
